//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diplom_reliz.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int IdDelivery { get; set; }
        public int IdOrder { get; set; }
        public int IdMethodDelivery { get; set; }
        public System.DateTime DateDelivery { get; set; }
        public int IdStatusDelivery { get; set; }
    
        public virtual MethodDelivery MethodDelivery { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual StatusDelivery StatusDelivery { get; set; }
    }
}
