//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diplom_reliz.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int IdPayment { get; set; }
        public int IdOrder { get; set; }
        public int IdMethodPayment { get; set; }
        public string AmountPayment { get; set; }
        public System.DateTime DatePayment { get; set; }
        public int IdStatusPayment { get; set; }
    
        public virtual MethodPayment MethodPayment { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual StatusPayment StatusPayment { get; set; }
    }
}
