//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diplom_reliz.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.StatusPayment1 = new HashSet<StatusPayment>();
        }
    
        public int IdPayment { get; set; }
        public Nullable<int> IdOrder { get; set; }
        public Nullable<int> IdMethodPayment { get; set; }
        public string AmountPayment { get; set; }
        public string DatePayment { get; set; }
        public Nullable<int> IdStatusPayment { get; set; }
    
        public virtual MethodPayment MethodPayment { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual StatusPayment StatusPayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusPayment> StatusPayment1 { get; set; }
    }
}
